-- Fase 8: QR-vs-direct-link channel attribution. QR codes generated by this
-- app encode `?src=qr` in the URL (see src/lib/qr.ts); [code].astro reads it
-- and records the channel here. Anything without that param — someone
-- pasting/clicking the plain short link — is 'link'.
alter table public.analytics
  add column channel text not null default 'link';

create or replace function public.record_scan(
  p_link_id uuid, p_country text, p_city text, p_device text, p_os text, p_browser text, p_utm_source text,
  p_referrer text default null, p_visitor_hash text default null, p_channel text default 'link'
) returns void language plpgsql security definer set search_path = public as $$
begin
  insert into public.analytics (link_id, country, city, device, os, browser, utm_source, referrer, visitor_hash, channel)
  values (p_link_id, p_country, p_city, p_device, p_os, p_browser, p_utm_source, p_referrer, p_visitor_hash, p_channel);
end;
$$;

create function public.get_link_analytics_by_channel(p_link_id uuid, p_from timestamptz default null, p_to timestamptz default null)
returns table (channel text, clicks bigint)
language sql stable set search_path = public as $$
  select channel, count(*) as clicks
  from public.analytics
  where link_id = p_link_id
    and (p_from is null or scanned_at >= p_from)
    and (p_to is null or scanned_at <= p_to)
  group by 1 order by 2 desc;
$$;
revoke all on function public.get_link_analytics_by_channel from public;
grant execute on function public.get_link_analytics_by_channel to authenticated;

create function public.get_analytics_summary_by_channel(p_from timestamptz default null, p_to timestamptz default null)
returns table (channel text, clicks bigint)
language sql stable set search_path = public as $$
  select channel, count(*) as clicks
  from public.analytics
  where (p_from is null or scanned_at >= p_from)
    and (p_to is null or scanned_at <= p_to)
  group by 1 order by 2 desc;
$$;
revoke all on function public.get_analytics_summary_by_channel from public;
grant execute on function public.get_analytics_summary_by_channel to authenticated;
